### ISSUE TITLE
[Feature request] Option to not re-download episodes that are deleted outside of Podgrab

### ISSUE THREAD

**Issue by DonDawsy** [akhilrex/podgrab#101]
I'm downloading video podcasts that are picked up in Plex, and I delete them from Plex when I've watched them. Podgrab will then download the episode again when it's missing. Would be great if there was an option to only download episodes once.

**Comment by akhilrex** [comment]
Please delete them from podgrab instead of Plex if possible. Or delete from
podgrab also after deleting from Plex.

If an episode is not marked as deleted podgrab simply assumes it to be
missing.

Thanks and Regards

Akhil Gupta

**Comment by shooftie** [comment]
Sorry to dig up this old issue. I see that you've closed it already. This is actually causing me quite a bit of trouble because the drive that Podgrab is downloading to is filling up very quickly. The server on which it runs is used by a number of people and is currently downloading around 100GB a day of podcasts alone.

My previous solution was to run a script that pulled the podcasts off this drive and either archived them or synced them to various devices.

Last count was almost 30mins to delete all of the episodes via the UI. Is there absolutely no way of adding an option to the settings, "automatically download missing episodes?"

Podgrab is, hands down, the most appropriate solution that I have found to date, save for this one single feature that is rendering it nearly useless for my case.

I don't write GO, I do do Vue. If there is anything that I could do on the front end in exchange for this feature, I would gladly do so. Just say the words.

**Comment by akhilrex** [comment]
I appreciate your gesture. I'll look into it.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
> Sorry to dig up this old issue. I see that you've closed it already. This is actually causing me quite a bit of trouble because the drive that Podgrab is downloading to is filling up very quickly. The server on which it runs is used by a number of people and is currently downloading around 100GB a day of podcasts alone.
> 
> My previous solution was to run a script that pulled the podcasts off this drive and either archived them or synced them to various devices.
> 
> Last count was almost 30mins to delete all of the episodes via the UI. Is there absolutely no way of adding an option to the settings, "automatically download missing episodes?"
> 
> Podgrab is, hands down, the most appropriate solution that I have found to date, save for this one single feature that is rendering it nearly useless for my case.
> 
> I don't write GO, I do do Vue. If there is anything that I could do on the front end in exchange for this feature, I would gladly do so. Just say the words.

Hi

I have done this. Please rebuild this container and toggle the setting in the settings section.

**Comment by shooftie** [comment]
Do you want coffee @akhilrex!? Because this is how you earn yourself some coffee, damnit!

You champion.

**Comment by akhilrex** [comment]
I am happy just to know that people are using my projects and they are
making their lives easier.

Let me know if you find any other issues.

Thanks and Regards

Akhil Gupta

**Comment by shooftie** [comment]
I will continue to make feature requests and follow this project intently.

Holler if there is anything that you want on the frontend.
