### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by undaunt** [akhilrex/podgrab#12]
Hello!

Thanks for making this app, it's great. I had a few questions on possible features. Could you possibly add:

- ~~Ability to sort podcasts by name / last episode / date added type of options on the main page of all podcasts?~~ **- DONE**
- Add a download all episodes button to each podcast's page instead of only from the main podcast list page to prevent needing to nav away for downloading all
- Pass through UID and GID along with time zone into the image for permissioning? I frequently pass through all 3 in linuxserver images as: TZ, PUID, and PGID. Right now everything is root/root.
- For podcasts where their main image fails to load or has no image, extract an image from a recent episode file so the podcast image is not left as default. (Eg: https://feeds.fireside.fm/selfhosted/rss)

Thanks again.

**Comment by akhilrex** [comment]
Great suggestions. I will definitely put point 1 and 2 in pipeline. Point 4 could be a little tricky since the logic of displaying the default image is all set on the client-side which kicks on whenever any image (across the site) fails to load. I will look into this though.

About point 3 - I'll be honest I have really tried to do that and gave it a fair bit of time. I am REALLY new to GO (built podgrab as a learning exercise mostly). I think I need to get someone much better with Docker to help me fix that. If you can or know someone who can look into the docker file, I'll be grateful.

Having said that I will definitely invest more time in this myself to figure it out.

**Comment by Code-Slave** [comment]
you can use --user puid:pgid now in docker command line

**Comment by undaunt** [comment]
I saw you added the sorting options. This is great. However, there appears to be an issue with grid view formatting with podcasts that have a long name. Please see below:

![formatting](https://i.imgur.com/gP95QV7.png)

**Comment by akhilrex** [comment]
This is actually quite tricky. I have already tried many things here. Do
you have any reference link as to how other apps handle this layout.

Trimming titles after a certain length should do the trick. What do you
think?

Thanks and Regards

Akhil Gupta

**Comment by undaunt** [comment]
Pocket casts simply uses the header images as such:

![here](https://i.imgur.com/NYA9dz3.png)

Perhaps since you'd still want to list the buttons/etc., put the last episode directly below the images and eschew the title text completely in grid view. Most podcasts are easily identifiable by their cover art.

**Comment by akhilrex** [comment]
Good idea. Done just that. Pull the latest image in some time.

**Comment by undaunt** [comment]
Looks great, screenshot it including dark mode here - https://github.com/akhilrex/podgrab/issues/38#issuecomment-773470759

**Comment by akhilrex** [comment]
Almost all of these are done. There is another dedicated issue for UID/GID which will be tracked there. Closing this.
