### ISSUE TITLE
How to change save location.

### ISSUE THREAD

**Issue by Iceman253** [akhilrex/podgrab#308]
Hi, I was just wondering if there is a way to save the files to a specific location on my computer.

**Comment by muse-sisay** [comment]
Hi @CodeKid2024,
It's been a while since I have used Podgrab so take my answer with a grain of salt. I am also going to assume that you are running Linux. With that being said, you can specify the download location with `-v` option. Inside the container it (Podgrab) downloads the files in `/assets` directory. So you can do something like this `-v "/host/path/to/assets:/assets"` to download the files in `/host/path/to/assets` path ( your machine(. You can use `pwd` to get your current working directory.

If you don't specify path to mount `/assests` directory, it writes/downloads to the container filesystem, which is not persisted.

```
docker run -d -p 8080:8080 --name=podgrab -v "/host/path/to/assets:/assets" \ 
  -v "/host/path/to/config:/config"  akhilrex/podgrab
```

I hope I understood your question and gave you a satisfactory answer,
Muse

**Comment by Iceman253** [comment]
Okay. Just so you know, I'm not running linux but I do have WSL installed. I can get it to run on my browser, but docker always pulls the repository itself and ignores the asset folder I'm providing so I can't get to the mp3 files that are downloaded.
![image](https://github.com/user-attachments/assets/2127e459-e65b-4641-8f94-7686018d43de)
It keeps giving me this error, maybe it's a problem with where I'm saying the config file should be?

**Comment by muse-sisay** [comment]
WSL should be fine. But make sure you're your passing the correct path.

Can you post the command you ran?

**Comment by Iceman253** [comment]
`docker run -d -p 1624:8080 --name=podgrab -v "\\-----\Media\Podcasts\Podgrab test" -v "C:\Users\-----\podgrab" akhilrex/podgrab`
Okay, I just got past the error it was giving me, not a big deal. You can ignore that. Now I'm just confused about the not saving to the right folder thing.

**Comment by muse-sisay** [comment]
The format to mount a directory on your host to a container is `./local/path:/contianer/path`. Note the colon(`:`) between the paths. That is how docker understand how to map the directories.  You are missing the target path.

The command you need to run would be 
```
docker run -d -p 1624:8080 --name=podgrab -v "\\-----\Media\Podcasts\Podgrab test:/assets" \ 
-v "C:\Users\-----\podgrab:/config" akhilrex/podgrab
```
It's been a while since I used Windows or WSL so make sure the paths are correct (`C:\Users\-----\podgrab`). Use pwd to get your current working directory.

**Comment by Iceman253** [comment]
Code Run: ``docker run -d -p 1624:8080 --name=podgrab -v "\\-----\Media\Podcasts\Podgrab test:/assets" -v "C
:\Users\----\podgrab:/config" akhilrex\podgrab:latest``
Error: ``Unable to find image 'akhilrexpodgrab:latest' locally
docker: Error response from daemon: pull access denied for akhilrexpodgrab, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.``

**Comment by muse-sisay** [comment]
It is complaining that it can't find the docker image for Podgrab. Looks like you have a typo. It should be `akhilrex/podgrab`. Linux uses forward slash`/` unlike windows which uses back slash `\` as path separator.

If you have more question you can find me in this Slack Server https://join.slack.com/t/kubefirst/shared_invite/zt-r0r9cfts-OVnH0ooELDLm9n9p2aU7fw . It is faster to give you help there.
