### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by Code-Slave** [akhilrex/podgrab#33]
as it stands all thumbnails for images for episodes and main index are remote. If my docker doesnt have external access for any reason all the images are dead. Could you at the minimum cache the main image for the podcast and even better to cache for episodes too. Although I think just the main image as the episode image would be more than ok

**Comment by akhilrex** [comment]
I am a firm believer in not having many external dependencies which is why most of the js/css used in Podgrab is also self-hosted. I had considered what you are requesting originally but dropped the idea because of primarily these reasons

1. Podgrab doesn't really work if the container can't connect to the internet. You won't even be able to download the podcasts if that's the case. 
2. Images will only be dead if the client device this is being used to access the podgrab instance is not connected to the internet. If you are connected to the internet on your phone/computer even if the podgrab instance is not - the images will continue to work.
3. The system has been build to gracefully fall back to a default image in case of image failures of any kind. This should handle the extreme of the extreme scenarios.

Because of these reasons, I don't think there is any need to build this functionality. The dev and testing effort and the extra storage overhead do not really make sense in this case.

**Comment by Code-Slave** [comment]
My scenario. I allow external access once a week to grab episodes. Otherwise i access it through my local network. I get what your saying, but what happens when a podcast goes offline? you lose all original artwork. I archive history and story podcasts so when they are no longer available online then there is no longer access to the art.

**Comment by Code-Slave** [comment]
just to add to this. when you display episodes for a podcast you need to make a call for each episode. some of the stuff podcasts have 2000 episodes. thats a lot of unecessary traffic

**Comment by akhilrex** [comment]
Hi

You made a solid point about a podcast going offline. I have added the ability to enable download of images as well. Please rebuild this image after the build is complete and enable the setting on the preferences page.

Hope this helps

PS: Podcast cover is not being downloaded right now. Will work on it.
