### ISSUE TITLE
Integration with AntennaPod

### ISSUE THREAD

**Issue by mmBesar** [akhilrex/podgrab#59]
# Integration with AntennaPod

I posted feature request [here](https://github.com/AntennaPod/AntennaPod/issues/4960#issue-814638898)
An integration between a self-hosted project like Podgrab and an open source client like AntennaPod would be great.

**Comment by akhilrex** [comment]
I have initiated a conversation with the AntennaPod devs. Let me get some info about the integration and lets take this forward.

**Comment by mmBesar** [comment]
> I have initiated a conversation with the AntennaPod devs. Let me get some info about the integration and lets take this forward.
Great, thanks.

**Comment by akhilrex** [comment]
Seems like too specific a use case. Might not be useful to the majority of users.

**Comment by muse-sisay** [comment]
> Seems like too specific a use case. Might not be useful to the majority of users.

+1 I am very interested in this. Podgrab could act as a server downloading the episodes offline. And AntennnaPod could act as a client. 
My current setup is to smb connect to my server copy the files to my phone then refresh AntennaPod. I wish there was some kind of integration(automation), like I exporting RSS feed from Podgrab, adding it to AntennaPod.Whenever I sync my podcast it automatically fetch's new episode ( downloads/sync the files to my phone, instead of getting them from the internet).  Would be great if listening status is synced over both server and client.

I have been using Podgrab for around 2 months overall its a great experience.

 This is a feature that I really look forward too.

**Comment by coldshouldermedia** [comment]
> +1 I am very interested in this. Podgrab could act as a server downloading the episodes offline. And AntennnaPod could act as a client.

Another vote for this, as I mentioned in (since I didn't consider use with a pre-existing app) https://github.com/akhilrex/podgrab/issues/154

It would suit my needs perfectly, and I would love to see this kind of functionality implemented.

**Comment by darkzero-sdz** [comment]
Yeah, another vote for this. Any way to have a bounty on this too? Many users would love to have selfhosted cross-device podcasts with sync according to reddit selfhosted for example.

**Comment by dutrieuc** [comment]
Interested here as well, I see AntennaPod implemented support for the nextcloud gpodder app. Maybe we could implement the same subset of the gpodder api so there is no need for extra code on the antenna pod side ? I would be interested in getting started on it if you think it's promising @akhilrex 
https://github.com/thrillfall/nextcloud-gpodder
