### ISSUE TITLE
Linux Install Instructions

### ISSUE THREAD

**Issue by dannyhanes** [akhilrex/podgrab#61]
I know I know... docker is the future, but I am not part of that future yet lol. 

At some point I would love to install this on a fresh Ubuntu Server install minus docker. 

Looks great!!

**Comment by akhilrex** [comment]
I'll be honest. I have been wanting (trying) to do this ever since the application started since it being only available as a docker image really narrows its availability. I have wanted it to be a simple cross-platform installable utility that you install once and forget.

I am really new to GO and am not able to find good resources that I can use to build such installers. I am working on it and will deliver soon. If you can, or know someone who can help, I'd appreciate the help.

**Comment by akhilrex** [comment]
Hi

You can follow the guide at the following link

https://github.com/akhilrex/podgrab/blob/master/docs/ubuntu-install.md

Let me know if you face any issues.

**Comment by dannyhanes** [comment]
@akhilrex Great, thank you! I'll give it a shot this week and let you know.
