### ISSUE TITLE
Scan folders for existing files

### ISSUE THREAD

**Issue by tehniemer** [akhilrex/podgrab#8]
I'm coming from gPodder and have a fairly large library already built, is there a way for podgrab to scan the existing files and mark them as already downloaded?

**Comment by akhilrex** [comment]
It could be tricky considering there could be many different ways of naming the folders and files. Let me explore this in a little more depth.

**Comment by akhilrex** [comment]
gPodder has a really weird default naming convention where they keep the original filename and then append some unique identifiers to it. Podgrab renames the files using the episode titles. It would be really difficult to match both of these without actually downloading the file first and then doing a data comparison which would be the same as re-downloading everything else. 

What you can do is use Podgrab to monitor only future episodes so that there is no duplicate data. Closing this for now.
